package gen_fiber

import "text/template"

var tpl = template.Must(template.New("assets").Parse(`// Code generated by fiber-gen.go - DO NOT EDIT.

package auto

const Generated int64 = {{.Generated}}

func Assets() map[string]string {
	var assets = make(map[string]string, {{.Assets | len}})
{{range $asset := .Assets}}
	assets["{{$asset.Name}}"] = {{$asset.Data}}{{end}}
	return assets
}

`))

func Entry() (error, string) {

	return nil, ""
}
