package templates

const PresenterTemplate = `// Package {{.Package}} code generated by team142

package {{.Package}}

type DataSuccess struct {
	Data interface{} {{.Backtick}}json:"data,omitempty"{{.Backtick}}
}

type DataArraySuccess struct {
	Data        interface{} {{.Backtick}}json:"data,omitempty"{{.Backtick}}   // Data is the array of data
	ReturnValue int         {{.Backtick}}json:"return,omitempty"{{.Backtick}} // ReturnValue is the number of items returned
	Limit       int         {{.Backtick}}json:"limit,omitempty"{{.Backtick}}  // Limit is the query limit, what was the query limited to return
	From        interface{} {{.Backtick}}json:"from,omitempty"{{.Backtick}}   // From is the first id
	Next        interface{} {{.Backtick}}json:"next,omitempty"{{.Backtick}}   // Next is the next id
	Total       int64       {{.Backtick}}json:"total,omitempty"{{.Backtick}}  // Total is the total number of items in the query
}

type DataError struct {
	Message string      {{.Backtick}}json:"message,omitempty"{{.Backtick}}
	Data    interface{} {{.Backtick}}json:"data,omitempty"{{.Backtick}}
	Error   error       {{.Backtick}}json:"error,omitempty"{{.Backtick}}
}
`
