package templates

const RouterTemplate = `//Package {{.Package}} code generated by team142

package {{.Package}}

import (
	"{{.Struct.HandlerImportPath}}"
	"{{.Struct.MiddlewareImportPath}}"
	"database/sql"
	"github.com/gofiber/fiber/v2"
)

const (
	RoleRead{{.Struct.Name}}   = "read_{{.Struct.APIName}}"
	RoleCreate{{.Struct.Name}} = "create_{{.Struct.APIName}}"
	RoleDelete{{.Struct.Name}} = "delete_{{.Struct.APIName}}"
)

func {{.Struct.Name}}Routes(api fiber.Router, db *sql.DB) {
	api.Options("/{{.Struct.APIName}}",{{ if eq .Auth true }}
		middleware.AuthMiddleware(db, nil),{{end}}
		handler.{{.Struct.Name}}Options(),
	){{if eq .PrimaryKeyCount 1}}
	api.Get("/{{.Struct.APIName}}/:id",{{ if eq .Auth true }}
		middleware.AuthMiddleware(db, []string{ RoleRead{{.Struct.Name}} }),{{end}}
		handler.Get{{.Struct.Name}}ById(db),
	){{end}}
	api.Get("/{{.Struct.APIName}}",{{ if eq .Auth true }}
		middleware.AuthMiddleware(db, []string{ RoleRead{{.Struct.Name}} }),{{end}}
		handler.GetMultiple{{.Struct.Name}}s(db),
	)
	api.Put("/{{.Struct.APIName}}",{{ if eq .Auth true }}
		middleware.AuthMiddleware(db, []string{ RoleCreate{{.Struct.Name}} }),{{end}}
		middleware.Verify{{.Struct.Name}}Body(false),  
		handler.Save{{.Struct.Name}}(db, true),
	)
	api.Post("/{{.Struct.APIName}}",{{ if eq .Auth true }}
		middleware.AuthMiddleware(db, []string{ RoleCreate{{.Struct.Name}} }),{{end}}
		middleware.Verify{{.Struct.Name}}Body(false),  
		handler.Save{{.Struct.Name}}(db, false),
	)
	api.Delete("/{{.Struct.APIName}}",{{ if eq .Auth true }}
		middleware.AuthMiddleware(db, []string{ RoleDelete{{.Struct.Name}} }),{{end}}
		middleware.Verify{{.Struct.Name}}Body(false),  
		handler.Delete{{.Struct.Name}}(db),
	)
	api.Delete("/{{.Struct.APIName}}/multi",{{ if eq .Auth true }}
		middleware.AuthMiddleware(db, []string{ RoleDelete{{.Struct.Name}} }),{{end}}
		middleware.Verify{{.Struct.Name}}Body(true),  
		handler.Delete{{.Struct.Name}}(db),
	){{if eq .PrimaryKeyCount 1}}
	api.Delete("/{{.Struct.APIName}}/:id",{{ if eq .Auth true }}
		middleware.AuthMiddleware(db, []string{ RoleDelete{{.Struct.Name}} }),{{end}}
		middleware.Verify{{.Struct.Name}}Body(false), 
		handler.Delete{{.Struct.Name}}ById(db),
	){{end}}
	api.Trace("/{{.Struct.APIName}}",{{ if eq .Auth true }}
		middleware.AuthMiddleware(db, nil),{{end}}  
		middleware.Verify{{.Struct.Name}}Body(false),  
		handler.Trace{{.Struct.Name}}(),
	)
}
`
