// code generated by team142

package router

import (
	"code-gen/example/basic/handler/v1"
	"code-gen/example/basic/middleware/v1"
	"database/sql"
	"github.com/gofiber/fiber/v2"
)

const (
	RoleReadUser   = "read_user"
	RoleCreateUser = "create_user"
	RoleDeleteUser = "delete_user"
)

func UserRoutes(api fiber.Router, db *sql.DB) {
	api.Options("/user",
		handler.UserOptions(),
	)
	api.Get("/user/:id",
		handler.GetUserByPrimaryKey(db),
	)
	api.Get("/user",
		handler.GetMultipleUsers(db),
	)
	api.Put("/user",
		middleware.VerifyUserBody(false),
		handler.SaveUser(db, true),
	)
	api.Post("/user",
		middleware.VerifyUserBody(false),
		handler.SaveUser(db, false),
	)
	api.Delete("/user",
		middleware.VerifyUserBody(false),
		handler.DeleteUser(db),
	)
	api.Delete("/user/multi",
		middleware.VerifyUserBody(true),
		handler.DeleteUser(db),
	)
	api.Delete("/user/:id",
		handler.DeleteUserByPrimaryKey(db),
	)
	api.Trace("/user",
		middleware.VerifyUserBody(false),
		handler.TraceUser(),
	)
}
